# do not install anything extra onto the image
language: generic

os: osx
osx_image: xcode10

# branches:
#   only:
#   - build

notifications:
  email:
    on_success: never
#    on_failure: change

cache:
  directories:
  - $UNITY_DOWNLOAD_CACHE

# decrypt the encrypted SSH key file so it can be used for scp auth in post_build.sh
before_install:
- bundle install
#- bundle update fastlane
#- sudo -E sh ./Scripts/before_install.sh
#- openssl aes-256-cbc -k "$KEYFILE_PASS" -in "${UPLOAD_KEYPATH}.enc" -out "${UPLOAD_KEYPATH}" -d

#install:
#- sudo -E sh ./Scripts/install.sh

script:
  - cat ios_segment* > ios_combined.zip
  - unzip ios_combined.zip -d .
  - cp -R ./fastlane ${BUILD_PATH}/iOS/
  - fastlane beta build_number:${TRAVIS_BUILD_NUMBER} project_path:${BUILD_PATH}/iOS/ build_root:${TRAVIS_BUILD_DIR}/
#- sudo -E sh ./Scripts/build.sh

#after_success:
#- sudo -E sh ./Scripts/post_build.sh

env:
  global:
  - UNITY_NOPROXY="localhost,127.0.0.1"
  - UNITY_DOWNLOAD_CACHE="${TRAVIS_BUILD_DIR}/unity_download_cache"
  - UNITY_PROJECT_NAME="TravisUnityProject"
  - BUILD_PATH="${TRAVIS_BUILD_DIR}/Builds"
  - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"
# fastlane app specific
  - secure: "jTG/3r70XaP1+K8K9UX5GGmpizI+xsXpvdySGS0MJrd3bs/vfOoIu3oVU5h63uR+U8qMCpjpaoQDuDlWVqd3+kpM6xNr6Mrmqvlhq49Cyc+I4xqqRXkwTWa9bSy/PAMDEGr5ATp1yQjWVKj6XqkiwOIe+js4XqKbZoBn43f0ESP+CvVJfVRIS4zNuFdTjyzMC/23iat1cDGu8SOUgGOhr4Wdi5hMxmadeoE45IBaFOjbQ6QaltX+K0U55Vx/91xlHYB9FCwnDgIpvxNjNOPKtZJDmXhiX7Aw6bszgYemGFUM8+6+rc2WRTEVPfXTHGROtQvcjmubQjcsIr2LsTgliKFmdhz+9d90JRj/H7wzYWlMNoHnnNvPJ438XMqbN4W8ggs4IgR676bTa74Dc52tSxK/HQPjfdc0S1pmMUvF9be9NSiUD+ZlyqsFo9sLwov3bkCYABzcDw505lBKQfPAWTR3uwuv3QkRZnE/xfa9ynoGcgwNAr/Hoa4qOH2QE7/jLzvSV48Ns/5Apu+KYcBmDV7ayM5AwGKijUrNcF4WGBT7r3blvPvOqlQPLnxlPO3ijsvE673zJt5wVtXETLpZfJteNgIyP3UOGpHR0k2IHXM8m1cY2Korps0/vvXGHUaDXTBR/oJ2eStrALPnspqiljU8xnd2QwgUHxKCxITqs9Q="
# fastlane password
  - secure: "FICZ2Md3q2JjKkwFB1FWJznS1kciL84xOKcVcHfn305D3RxVwg0wYG5cCZUljtfRTl2C5aF/hBnINLleeVnEY3EqEiMeBl8CtEdMy1h+Mn2SMpLwANYVI0NcrMfdHPHQ8jK3eNIt3PIUFnBNv3vf2MyElP6mNQWCZ+YCILz4T6mVKoWzAMeHjy/AoOpoTwECK4eZbbvG8aRnWm/deQYf/qVBkGZCJiNlgjcIqOU80vq5RIP5BtFpXVPzzFE9TQ4a6h+qSooatlxPfzlJm5mcMzNSFkj+sxc+NYBladkLa8gdOZiD8eUw79KUxCcLW58+2ziflzQCTCmFMUvtxYlcR6J3dsXNBTjGv2N0ozztDp2sS+kE1dY8QopZ8Mjq6MQFpozN/U1DKn5shYsKHrMV0Wi5jCUnlL7+Xug5RfvFrF619+3Kl74xKGmmwNkzjU+Uv6kStKyrSwBJRGk8EcG68T4jH7GOyA5OVMntRt7Eb7oZsZCzltlcax2PLe4a90GEJSSn6Xf79Z4MP94OurWOVKj1jxgmXubGrfAzhCPS0hpqiSGpogVRnv9RNkrl3Fg4BnHr14/mLXOtWC/gC8TDAFY8pkQd/Az0sNzSSBzowVJLOvS0kuJV2oqVg5fRKaosLHvY0jltmldH7neqOPiAjPI2KfSXrP2QnwKqQRUdWEI="
# slack url
  - secure: "piHzM825sCU6diW6Tschug1FP5HavmTXALwhQdBE6Zq147z6PWDKknnLBBAneoe6RcnTdJkKAXp7679/vCYlmavlBj+wmp1hF8ukMBCEaq0r0jN++ty9wYQt3YlCD8xhDSxt7jtvtpOp5q2dMj87/zr2giqA5yWhK9K9jWjFJ2yi2ktUTNFzlvtYAjTM1ho5H9Z6seL4mYEyoL0P0r3Wa+a89PzQ960h2dJYBH7dJ9OSphuE5vhRGK6UjYj1WLJlR2ds0s3oZKpKvQCikL4Cnm48VEUJsNioXfwrjnbKw0VkTSkrx3jlzUbRqMuUeOym7UDoHCwxVMQWXpGKLuwwoWU2dKANrTXcAxkjBNe47mBvDPw1JS49rJojms5f9YHOln8Bb5fyIsiSfDXNdU6L8dfI7KY1gtlpls8dkS3/nNrtkBOnsbSK7CZVE9m8QnI0yg6Be5EuOdGwZYyTAHBgP9UYAovaGi6u3M23bDjEHMOpnxbQBqa1AtINnqIxfK3+NyX5VtgXzn9vzDNkNlFtkIOUddy3+gj2prAY3wwsJmfLNuDuesGNuhVccEvwFsjV7Jaxrbcnx/c8fcYjopwrAfyNu0+N0oK1VvO5yyNVfjWjVy+YioudWNw7szDZcunFmbItGFbVnmTnhP9TrRemge6qwO4Rl5UZDtWS28pEMQ0="
# match pwd
  - secure: "qUfO9eFUbrVyNsXqc/vccqI+fFfCKgqzcuvE5onfUH4D7SrVzHdWCUVTTQVyYnLPlPhHCtBllYexDa0Inybn+PLhAmheRwRGTKwOpMVhS0fhh8Vansnwx2nFTQUQq2OYT/nD8vzxX27VGqXnNuvp42KKv12rPsxRHLz10b1nybUkXXBqC0By/DSE4c1vO9MA7weUdwA9ajH2kYagEsmOD49COVIeTGI7xt1Ns9Ys149l9FbzzEQjxCvKfK8uQ0IEzFCYUwj3yKCfHS1awXY1KyTyWalRKJrThAqyfe7c49DezWF9BTurhaTnezPUeH1LZ2SvKheTvF4kESdobdo8zPoLH1NPz1t7v0QoEldHXfdyi7CiTatXnL3C59zg4FnwM0iLKzai3jsPC/H8nR3BbWYgIKvPdrY+ljE6QqI0sEYqhsDyZTu4PksxE0T1+UCjU/aLiGh9TnDNV4nOyAWDADLE4DUkuRDLEU76eJ2aD8wHyuYr7kP3BthoUjZTUO3ie3u66bljDGh2ft1ZVjlMRJUcY1VI8G3D3HnAU5qtUhalX6eqX0EnL1pmh55A8wLAyy8nzBv0uHonAQFzA1LUiZiFK/45XOzDgdZb9YwN00l9QxAtSWYSdLIa9mjk+2sTpx/K+Q44bGl6Lt2Mi16FTFB8tAFHsKbCTvuqL9Nuhh8="
# match keychain name
  - secure: "BmcFq7Q3uvBkPG9NtGMNRPNF5Jf+9jztqI64fNfa8yhnK6ww2un46xWIwWTPduHDjQgwX7y1VcVL7WSgYZpODUIv37IMVzCuhHUWS+Gzsb007TPS79iEDF6pyJcybP6vgnsQmRn868oAi9eJqTQFmQlvEU2RWRdl9l012jAz3PGTZ6XVI44h6akMck/foK8kfK6tFKaidX1f+ng3Qec4m2XF9NP/V9EdMLz75KNv28pPVMNhQid96QaBcxMVQ14ErfTzVrbkvACksDJXBK49LpPgICLxLyc5ynXqupcR63qtK2a6c4FO3nam605Gx24fj7Vk9UmFonvCff450W1zawUryAL+ZuE3jG2gMpmud0Kzc+R8/smkXLzZiCo+HecDo/HXrn19TdGg1VMgGShRdjygn1QJCoUOqcAjQj10R88QyKetF0InWPOQqaP9kF4vQ9PBK5LF4/fWVDRbfsjU1mPrK7qjUBj0KW8fV2WMan/Vec43gZ6dx74zDeyVkex1bs8EC7YRPeAMG+kW+Mt+0+gxs9jzl8e/+AEg3RR27eKxVSHmeMcGYLq//U1osYeA6HKhkfA9K5L+a/qi2bmYOnnpiSe05IpVtQEIF2TsRXBcBOi8rjixs7o64HZ01KVft2SKcX4+kmst0OJdcN1h64M3mCH71JU1tJTfV+180JY="
# match keychain password
  # - secure: "oE78vKj2/yRvScqCz8gALN4yQGUjmlrBGcU6k2rzBN26MIXTABAAjBOqWXr7pJgEQL8Og/ozcUOA9EnD46lTphqQjrIuqCW5A5OuhZ85bYbjv+Xi+CEdDbE5krCecmiT2EhMBKjl1YUYbcLh3Q+J868Gphnxe3Aou8kNUc02GMhzH17nvKdHMYhDrrn4QNJx/xEYaK+f5ZQXuNAetNpLJHeSp/pbLzWncOMq0XBWT6xkM4C6/Djceiclq77gW2U/Mbl3aYnFAXH1h2b9DFFz+AaxzULdFlhRl5i+DKXCRqK7u5r8ZwCsT68jcXVSSnuz/cE4vYoiUzW4Y/oT1lVliBqMgM0/ogSLUPW8YdwHEmGOGa2OoNkdlq4q/EHKPt+ibOssidpba33E6sPLiv4u5EhMgiaQCdsGSc02VQ94jIO+Vr6+edJWEvlu/AbugPnIw+kk3kN+qAaeTGd+W2miIi7L+CGqGIE82lstWHVZkbsZTlAvfc4sKtIylS1hV8uNmTEtnUlxAGOkSQO3Zdc8TeIpWSKX8S4e9saxEaYSd0bKmjvH/JhSDRT38rTVzIVQO5g9ZMYQac+xSgq+5TuUyVS8WEu9jEvxbwDpqbuaDJBzV1NmOqHIMOPVznypvHLXhVya43TrNkoYWgEfFE00ydNDoK1Q8gxbJ0WpHNoynA8="
# unity serial
  - secure: "lqiGi4mcltGwUFkUrzdtaeHGqMSfkwLMnEUJwHboeZ4PDM3rW28V1LkQBD55eKii06rTJpM6wBIA3KIghgXQQGyphjhuQuYfCZBT1dhpE4xahyFXFsYXcnwH8RxdFsf2HmaTkkdV1sF1ulPOBvsBAiipqJ9PSU5dnBnR9nxl4pIHGv7QUa7yoLP2ZMfx2Yg1uvuXv6J4XdcLmrkoCPcGTBhpwnN9XcYM8rwUKmNLEHl5me2eVVpOBRu8Rwk2Y2WK3iLEy6y2B2rD0mEVzzcfYizIFelycFJJPXJGsoVrak5O0LLArGHr2TQuhn7CuTGHsQDZNxGyslESQmUyYVjrPySUREX1buRiQmbrWXfErP/P8cYSo6bETLUHXSeM2TmRD2ZvHeCSFL7O02dE80EPxkxO0oEwPoK7fVCAl8wEqWakIlFqHJsgzScjAuJOPtJIpEC8il42tfo3O2UBpCCGk6yVtzc1HVwIx4EKoDla8Ljl39rsmPWvFOnKrrdkA9x+IREMcUsC5jdBKhcpR9TAsNtKlfiSC1LF4KpGZBn4OocD6uJ5P1VR72eWgMm3iz52BAK+aVnam7xCYvROrtEISw/BiiGq78HxSDsDvI1YNv49uZsHKSWcYLY+EwbQQ+RMtvYJ8cTKBsa8KEIM2zgfMefq2x5D1TMvi8dP7kpByhY="
# unity user
  - secure: "GTC8A0LdTvqPTXb8ltli3BgdrQKp1m9lKeGT/aS54U4aMiUWZTnQEUTii2R2rMzThkMcVkBzV9JDqcXU+ytCy5Fzj5wAe2UDAzLcE0pjF2OMHd8hXaCP58gN/UTCr8ildJoyZYqcJ1+wqMfrAFXR6xQAgCoUz2p2k063QLOogbcFi3hre0ye4TqAB57I8kU59CHbYS62If1o2W2DoCoh73pLIvcU7QN84lFydba0vAmCRg+9lb/xp3mcAsVLNYPBd5OuaDFsVyn7s1hpol9RiPMswbPprnthonQacKDBtD4jrjWX0mCHXOHVi0v2canfVuHNSryHWlSjCzvve9brN2BxjKne440Q7VLX3YDwchee9V/moC4XqjTwgqu7JXblDc0HT4ArJYin2lWF3X6A5x9KvTU5wNqT5jSTyTxwWtkZvpuJw7QFc25LVbMfYl1+/R0RA7vFORfUqUglVkeED3un9oXP3MzYURf1llDnmPpT/vqocDQlPfrkZ2cqfwzt/6T8a9O3XAD8TIv4M5Liyz0Ick3GDjIycznK6/0tkE1Mx1iptxur623Rff0WrwIoyeo5KnwFai25FKNHfPdgNFM8qg2j++mUx8vOEZcBqX4kHx40EfcA96PvQfIifxGcnzlo2QGhbbVi+f1+CpmPRoq8hQA9IhxV1tG3OxxUnvk="
# unity pwd
  - secure: "JsP7NWBT9Q5L9wEEtkZJPNo2Ney1I5y12kk/l9aWa0aB+msSrnI3j8llG3w5NklRlLLhA7xVXII/NI0AsR/FgoBaVIt84YqFwH5HPfpaYB0kYfVnl+6W3j8D1JxvLiqN6wnqYL+8FTPbU3vDaYa8Dnb+J7zXhxkBizCOtXUDEBsg3U3NnF2HBizGbcy7Ty8CuaLgGy5YGIwDVeTeVsW8opGEqIQ1QTLhzVdMcDqAo5AnCQHygAMpun3hOGHQvkzPCcprB/5On1BFAreyGX8IalImTSEPVuZ38yC7sDHsZqD8lCcag4ybz02OI3q6wcQf9P2lG4mOIxn97Ixax6dd6JbknD/VSwg4P/rHPpKtlHDG6PVsB+lOUP7xtgKEXggxOo2DJGFfm8iCX4JL3LqYJ8WYYdaphyoZPfVrZPqgPkE+EZFKIdFKWGIRbuiQd0cXeJ1mA3tLo7JN6djfqKYhIK2jjunvV0ge1nwzuwy5tj71GBEHgeAgJ4D2AfHJsla5QVQ5Z9eNU/KecWLONLqNoHPIgPOrHNDLrXcS745S2l+w40iwP7v8ydkDhhUhiX3dpWsqXK03jSlTGo1BuPRiMXfVd6624yp7IRtVhGHJLj22ykFoiu9sx0QhAuxWX3eJj2Zoqs9TFUDZa0mfy0EsTVxvVtD0br5whyVwPCTcZrE="
