# do not install anything extra onto the image
language: generic

os: osx
osx_image: xcode10

branches:
  only:
  - build

notifications:
  email:
    on_success: never
#    on_failure: change

cache:
  directories:
  - $UNITY_DOWNLOAD_CACHE

# decrypt the encrypted SSH key file so it can be used for scp auth in post_build.sh
before_install:
- bundle install
#- bundle update fastlane
#- sudo -E sh ./Scripts/before_install.sh
#- openssl aes-256-cbc -k "$KEYFILE_PASS" -in "${UPLOAD_KEYPATH}.enc" -out "${UPLOAD_KEYPATH}" -d

#install:
#- sudo -E sh ./Scripts/install.sh

script:
  - cat ios_segment* > ios_combined.zip
  - unzip ios_combined.zip -d .
  - cp -R ./fastlane ${BUILD_PATH}/iOS/
  - fastlane beta build_number:${TRAVIS_BUILD_NUMBER} project_path:${BUILD_PATH}/iOS/ build_root:${TRAVIS_BUILD_DIR}/
#- sudo -E sh ./Scripts/build.sh

#after_success:
#- sudo -E sh ./Scripts/post_build.sh

env:
  global:
  - UNITY_NOPROXY="localhost,127.0.0.1"
  - UNITY_DOWNLOAD_CACHE="${TRAVIS_BUILD_DIR}/unity_download_cache"
  - UNITY_PROJECT_NAME="TravisUnityProject"
  - BUILD_PATH="${TRAVIS_BUILD_DIR}/Builds"
  - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"
# fastlane app specific
  - secure: "T+mdv3Wa5tB91P1kBr5zXCaMYKbC4CudXR+QyUo2TWO+YdjRooiYSW1eKCIQ599Ejft4DQHuuOf02R6LLMf+HwAhlYqrx5HCy1KBwR5U9xlxoklEUoT6whO5NOWJv3lbzao5d3m4IlVv6ex8AJhD0/39Voen49hpUAIUzLcrdMG/Z2GtoIZiJjrd4fjybYITIjIx+bs81XT0A8rpCVId1lOALKhZhqxcH8dBY6jzoGXVK8iU7KyC81Q96MO6RNrlTXXHlSrNX8ogZwEQeZqGE5TipPwH/LQrEAFKp87eYsF0EP/S91eOD7lAJPn6LsTDztEdh8TYjjkv8CA6xhaSzUUh1Nigg1n00bBwH6XHnBVZmAkw2SghVvSOsykcL2iv/HLzYdvSrtkd2F5WIaXWqaurPtWKBbM7Hw2wwgJ/8XTbTLkFqhPJstxI1Tmb/xnozpBI5BE9u3mekvBsIrgrXBQH74QgCVlR8WZSs41qN8UfNVnO5cBgC1aiSKpT30Y0AaVQBFc8MJgyCIdOwykloijnmz8UOaFo/JlDpZhTKcmY9QvxFfT5UK55DhTqEHdwL2TyzlYISSP63IpbgsP6JZ+RaYQEs5mdW2eS2WPyOV4Wi2es+uEAuL1ccPSeYZMZmki8MyES5IDxt3hqh/2vctF94wUFgm5d1xWZ1uRAB9Q="
# fastlane password
  - secure: "MoOeWOZFZeniJUgO5n2knQvz3sdcHEhi45vVKwZcyHVEWMaO7zZPQyktPHw4Kd6GFp0rJqKv/UDwzVIfC8HU3fnKvQ90xoEskJWPuPbG4hh0fMvG+WgJ/XgeRVjnOD7Vf32Bv7JqRxKCcXgZqFzRP3Y42OqRzoPHPGGqjMYpbI0RcwNLVdnz8J1qXy/VK33Io30MZH4UK6FBEw6bs/GsVRevjd4V7aMNuz9nTYPmayOPfZ2eOVevtEsRjA4/Xz5chzBNpI0nL25BYHxOyH1FhNUFCAYLQJg5JBVw1xbvCAAoInDN0VDeyFzC6GM5x070qIGSkr7ghjDQYn5uglfha2wIn5LIHRw12C/H4LwONVvlnTLYL+3dlu/yMpm6uEjpXeuDnEWfI6FAgnaBf07s/lFTRwsJSZgfz4eMhD+MmxgA6qF0cUE9JRSVNqF4yarsPzTzQECH4bjYhBPsDKKrIqdbys/EbflA4FWB3FXO/zp2GaD11S/W+jYS5H1l19325pdL86hbStdN8TFsWdIYuILpzFrwkQ246MTsHW2jgTErDG3K4vK9NDMCOZiQ1dN7ZHP019Hy9RkhEmnYxiP2i92oaGQBOfwdyIHBfwZEC4i/ybm412wDWVaxXAh8NJ1Oq9wZhkYZiz+J1gWIsE0ua4syRcUCuwP+XVEMo/kLous="
# slack url
  - secure: "GsXSe8tgNNL7dPWJsiYB4oaXrisHDlvBx8pOyPBEhYs8y796P/7Cb9d7hHt9HI5tS1LLlM3fQ/ogBfbtb4usiEnGxRazKcB98vWeuYyEAAqndk4Zlk32z1LEJPA4dDDy33R65VqhtI5zledKIPGCp5UK3NWSfge0h5rMlBsrM9XzT8oXEPLM15RF5A2ZlzG6HesWJMwi0aAz03Ehb0fpbty/5daQJ77eu4X/LvYL8vS/3OrG32D4F32qZ92RL32E9RM/iSLrRFhth+b3BenrI6rnUz9KefLqQ9zd4uCdfwVjsIcq/KKSbvlFOYx1ZmCyqQgBQSTLS/rAka1H2r0UDc9NirCoGRqxEriHkNbH9crq7z9IEQrpR7OzJag/++8y1gdJVV2HRSYG9kKoggF/MZTyug4ZVLI247swzOT7rvNwq2jKr1RwrF7AJftKwVX9ZreL6tKccPAhHawa3cDE4SkMlMHcJkp/zVmjtELoc42ZQ43Rjf9Fzty0S9nrPnaOaBYc71y+SRUoT+HtZyxlYmEOr7ktNCmsjjbc5Ax82rNQyEMRmYrnceaZt2wTvAF9XO6SN8uE8X0jkp8on8LUMvOH18odTqtaH8yuOJYK3s5FJ6nAExdSl84WknXSuv7ys7/O2SHEgB9haDkwxbJa44eZZpvM1JfKsNCpJ+elZKA="
# match pwd
  - secure: "gv6thR3Q2abol6Wc4SJTYUJO5HQEJZKyPv33tyiy5KOLCm4e11oh19uC5qDcRotXafYneCr6pomyUEvwpqw+B1KpiZk5/KxfnTCWO/vfLHUw9xoBevdqLBOEqpT5dr1B8Y65x7cJI23chpETpKcJcWTM1ZTBa5OWN+Dm/ZZNAVQVT3GvDD0/biMuDu+6rafIzhfl+G+w9AgwHzjH49pwFT52nyBcJcpEVO6fqkFUgTjm2TqshShBfFKvQG8LeZ8/xxYF9kcKV680v/7wj0783qBKQKR5lLTioFVZU0vazhMBXW/0nM6rhM6wJCUyb/iyTVauyyWhpJfTmccaOzBBAsN0xjCZEtuzlXhBAJtt+RjmrRL+FKC0jWZ4fMtk5FqUzm5frEx2XqumtNI+hiZ5crq/9Et3cqWVnlwyGzmxWlkeHNczUEjtje4Zxf81ch6TgpOxqc52t5LUBo6xqzoZ1k4TTsIaN7Ei7ahabXW0816zwfjKJsoRukYbGXBLbctGmnej4Z76rtbNh5zDyPTOvnMyGE0cWb9OP+FPh3CC0mu5uBEPPym7UWxpOdIXM5efWt+mRX72b6o+RwK6cazYMVNXlymlJmRcAMOKxM15q3HVrUyL/VPUZw44PjQOO21IEy+Nr0LkSWtM2Jjyj+QI/O9mV4qZDHk86ks/nbHtYJc="
# match keychain name
  - secure: "oADxfkfJj6I2iBn0tNIfEOBJatfdMFVslx0lxjec3BoBkqwDAIFpJYyYvoJZt+uOgTN13hM5m/89eyxafycI3g0ac1lahYpmp9tLlaMQE+VGmjzBRGTksDiFk8/rFHofqWeBHVZY/Rp9lkpvCoMRvZFUQMjQG0KSMUGuOTzB5eSWWtvJWI2LAGnne0WUPCXpfFaXAM6fXcUiUjweoTkVGOiCdusJn0JrdznOhNMaWuB4JNRhv/kh/NHKIWJypmdo5QusySFbLLjjrcCoAP1srf1wbmq2qR8i1hrrSCZtV8YCGZ4NapCT4GM2F/XE8jZwGGNkuaQDElPRvH/fPPfpfzubcnvIthUqXopWAh6ZhAd6Zc1aOdZDECYlImJy1RNtJrWUn63WX1TjlXlNOmn2jMn3EjcHwx4lnXUOYL0CMpoUpIcjSosukHzi0g0xQxHK1SbAW1z/OrOwxucawQ8C+qs6CBg7QQWax5yywGVe5YEaKM7OWH1/t9PibzH1UrUwmgd3WtXH8+dqnZdZb6IDk0fAZUwTWxAjA82fXTQpGAyggbZn0Lmnh/8HDDQ2vU3lNEQQqIv5E1UEs6wm1llks/W9irgreeydS7WiOlZmRrp/nh4f92vsZROnr7PL6f78h2Cporj9xbEV0mPg4XZyGDyze+7fXeLs2uhASpQ1W5w="
# match keychain password
  # - secure: "oE78vKj2/yRvScqCz8gALN4yQGUjmlrBGcU6k2rzBN26MIXTABAAjBOqWXr7pJgEQL8Og/ozcUOA9EnD46lTphqQjrIuqCW5A5OuhZ85bYbjv+Xi+CEdDbE5krCecmiT2EhMBKjl1YUYbcLh3Q+J868Gphnxe3Aou8kNUc02GMhzH17nvKdHMYhDrrn4QNJx/xEYaK+f5ZQXuNAetNpLJHeSp/pbLzWncOMq0XBWT6xkM4C6/Djceiclq77gW2U/Mbl3aYnFAXH1h2b9DFFz+AaxzULdFlhRl5i+DKXCRqK7u5r8ZwCsT68jcXVSSnuz/cE4vYoiUzW4Y/oT1lVliBqMgM0/ogSLUPW8YdwHEmGOGa2OoNkdlq4q/EHKPt+ibOssidpba33E6sPLiv4u5EhMgiaQCdsGSc02VQ94jIO+Vr6+edJWEvlu/AbugPnIw+kk3kN+qAaeTGd+W2miIi7L+CGqGIE82lstWHVZkbsZTlAvfc4sKtIylS1hV8uNmTEtnUlxAGOkSQO3Zdc8TeIpWSKX8S4e9saxEaYSd0bKmjvH/JhSDRT38rTVzIVQO5g9ZMYQac+xSgq+5TuUyVS8WEu9jEvxbwDpqbuaDJBzV1NmOqHIMOPVznypvHLXhVya43TrNkoYWgEfFE00ydNDoK1Q8gxbJ0WpHNoynA8="
# unity serial
  - secure: "To1TdWURVOUIDur3sKVyjLefGWFnVhLmhRCZuB0QMiyMuWy89v9xj5NjIUTNmhp9YKsEYPjMUip6nan512VTqpqUr7m9OjXcIyMqngd7hHegK+/B2vh/4TBZNyUGwoNMHp4NhoN11rznswxa3jZjfbsWVM7lmdaJTuFkHCMYZTYxJ9ALpXlwYJE0btlbMAgUh59WFv+kpBvVdsJqhjtL+xT0HOqr8q7kfZpWC1iGAIEcsrvxaJpnxkJ295J5tekfmgvY2pZEt0G8S2HoTL79wqSQSNiUznXHgw7d+J2HJ51s5LnxapkEho+HH8B0bbI27u5u/5f7kX9rv7G7LuP0ihnEFCL0dCodp00F9BuEgqJdwa5HRl0RQVt0b/3cPPVLCDBnkX+8464GBX6tVV8HKEifkv7+eMpSdRKNzUj5Yim1azylAmI2xz7e66+63huQpPaWc+c9pb3yWVVDN1hnG1HodAf9L0t12r6FxcJOf7PqopwJQMwCJSgPAQ5IzsmgtH1CUMosf/Sod4k+veqfVTTYPiilf1yyFCU8MErmXx7/2ZdKezWznlsg/bHMDOfXe0xi0af3eZR/g5SCL0gRUSQQtmdkSk0LjXnyZFqAk1odk3N3Z2CQa7ve6GoR9S3uvp7Hh9LR8AnatRV1SbLKMZlCi7NkSQLeJ2oQ74mN6Kc="
# unity user
  - secure: "G1tyzhtmIagcjzpoSzMBXw9nR0lmyxDoPBwLkHl18cNzV8silpGCMGNJ7Q4c0ODUHBlYB3wR8CaGqsqSjJ/xtQoC4XX6mChLpmdV14o1PSYe+QUZQhsUwuAyWKlFUHywqY3G0bdmMrL0/68/DjB/yOUz9IOsu6ObdMnleTbO4UhTudLZSlWFc7XeWQmn+wEEPhKhEHOomDjwpf1NEuY7phX8HZMu/ji1wGuXUsv0WuTyFKtHe7UbJlX4Gnu0hWVtmUHW432r8H84bHFrL9yovihwp/5VptVU/XZwf1PC1RwOoHpjYNWwGlDdvrYbEMki7v3PqqObadhSXtMlPqpnpnAt2f9bQuD4fAWZEj1HTfNjkRk+A1Eaci1NPRg9StOiNFmiK6cqoiEAEPB30kyFrah/Lz4gs9rNQvbvZ3wYF3sAbj3rL9TcTNgr8WCEvfJuXhTf9dT8XzCnBadbsoPMwqMxa9S4UK45cyTIfTPSza0xfYsZJQ8IBxvUszjyxprVas+QJDjsn1xkhDmUEg0/FqhNEmJ5iAOP46Wv26RsvBi/SndSfyoE1GJJSz6Rcb1O0TI5WPHOgV698pWKXwT4wnLhmSvhjrOPtDosGylalLgwDHxITn/Oxiz+owVolIigbTn8EPLsvJkPSuerYpDtlY2UbE1GwTnYsZUpZU7dyIs="
# unity pwd
  - secure: "qFZ14DxJEhPGyEqsXBYo4ZN/MsH9ifgi6U99z+i8MzxcKqjwa3DoB44lSpGYsKBDmE03/JCxLXIoMF4qJejqkSpzYyRVAPl9Gl6GXn4U+G8eTAXetIDb/tA3c+1stPFvHFn+sFhXSdpGWgdCOiIUFKaClsVL9fmUDMnNIXwKp6VRp9l+Ey+ITawAkYsrBcehebYoMrmYf8W3BC5AB5Qs9cnKBlPA1euJgopUc8urpYFsoIp+LoKGRga3K7cq5m96co5WXaxFgXUgSI4G9yhDLeBtVyqjjDeI7TW7wZoMGG20DWqFhaKT6CEm+LG3gdtr2/egYmDr6B5Zxx6q1ndIIY8wg/KmRsTZ/zzjHj6ODjkA02Kw38TJx0nLCd8yr4QGLxSpW8Jiiobxc1zURIbr4VhoSET44l0uoRJ3OhNk53Ve2PDMu3tD/aDbG+WqO2/g2gI+ajfMR93oChXANkwe5d47lbo+QcqQ2BTJWNoi6WtTH8B9kRD+IA5torHV9C1oJK8ZlqeHs7oa5wNnjr9kQLeyaBT3p3IdIFpVooLpbM8ICkAoUHOvSLubJzDaZA3P4/ycBQOvavm5e0vTOwUVdPG4pVMXQYdduWUVUIYctq6cS74X9cuPd7TpoYyHWqKxDB4m3FxQgsUdJeAUnJpoS4rPAJxQoTGz6YHijXcNhNI="
