# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.105.2"
default_platform(:ios)
platform :ios do

  # before_all do |lane, options|
  #   create_keychain(
  #     name: ENV["MATCH_KEYCHAIN_NAME"],
  #     password: ENV["MATCH_KEYCHAIN_PASSWORD"],
  #     # password: SecureRandom.base64,
  #     default_keychain: true,
  #     unlock: true,
  #     # lock_when_sleeps: true,
  #     timeout: 3600,
  #     # add_to_search_list: true,
  #     verbose: true
  #   )
  # end

  after_all do |lane|
    delete_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"]
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do |options|

    # setup_travis

    ENV["MATCH_KEYCHAIN_PASSWORD"] = ""
    # ENV["MATCH_KEYCHAIN_NAME"] = "test_fastlane"

    def ensure_temp_keychain(name)
      if File.exist?(File.expand_path("~/Library/Keychains/#{name}-db"))
        delete_keychain(
          name: name
        )
      end
      create_keychain(
        name: name,
        password: "",
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: true,
        default_keychain: true,
        verbose: true
      )
    end

    disable_automatic_code_signing(
      path: options[:project_path] + "Unity-iPhone.xcodeproj",
      team_id: "Q5L7576G62"
    )

    set_info_plist_value(
      path: options[:project_path] + "Info.plist",
      key: "ITSAppUsesNonExemptEncryption",
      value: false
    )

    set_info_plist_value(
      path: options[:project_path] + "Info.plist",
      key: "CFBundleShortVersionString",
      value: options[:build_number].to_s
    )

    set_info_plist_value(
      path: options[:project_path] + "Info.plist",
      key: "CFBundleVersion",
      value: options[:build_number].to_s
    )

    register_devices(
      devices_file: options[:build_root] + "devices.txt",
      team_id: "Q5L7576G62"
    )

    ensure_temp_keychain(ENV["MATCH_KEYCHAIN_NAME"])

    # import apple worldwide developer cert
    # sh("security import #{options[:build_root]}Certs/apple.cer -k ~/Library/Keychains/#{ENV["MATCH_KEYCHAIN_NAME"]}-db -T /usr/bin/codesign")

    match(
      # keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      # keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      readonly: true,
      clone_branch_directly: true,
      type: "appstore",
      force_for_new_devices: true,
      # verbose: true
    )

    update_project_provisioning(
      xcodeproj: options[:project_path] + "Unity-iPhone.xcodeproj",
      target_filter: "Unity-iPhone",
      profile:ENV["sigh_no.mandarin.travistest_appstore_profile-path"],
#      profile:ENV["sigh_no.mandarin.travistest_adhoc_profile-path"],
      build_configuration: "Debug",
      code_signing_identity: "iPhone Distribution: mandarin (Q5L7576G62)"
#      code_signing_identity: "iPhone AdHoc: mandarin (Q5L7576G62)"
    )

    gym(
      silent: true,
      clean: true,
      scheme: "Unity-iPhone",
      project: options[:project_path] + "Unity-iPhone.xcodeproj",
      configuration: "Debug",
      output_name: "TravisTest",
      skip_profile_detection: true,
      export_team_id: "Q5L7576G62",
      codesigning_identity: "iPhone Distribution: mandarin (Q5L7576G62)",
#      codesigning_identity: "iPhone AdHoc: mandarin (Q5L7576G62)",
      export_method: "app-store",
#      export_method: "ad-hoc",
      export_options:{
        compileBitcode: false,
        signingStyle: "manual",
        provisioningProfiles: {
          "no.mandarin.travistest": ENV["sigh_no.mandarin.travistest_appstore_profile-name"]
#          "no.mandarin.travistest": ENV["sigh_no.mandarin.travistest_adhoc_profile-name"]
        }
      }
    )

    pilot(
      ipa: "TravisTest.ipa"
    )

    slack(
      message: "Build succeeded",
      success: true,
      payload: {
        "Version" => options[:build_number].to_s,
      },
      # Optional, lets you specify a whitelist of default payloads to include.
      # Pass an empty array to suppress all the default payloads.
      # Don't add this key, or pass nil, if you want all the default payloads.
      # The available default payloads are: `lane`, `test_result`, `git_branch`,
      # `git_author`, `last_git_commit_message`, `last_git_commit_hash`.
      default_payloads: [:last_git_commit_message],
      # Optional, lets you specify any other properties available for attachments
      # in the slack API (see https://api.slack.com/docs/attachments).
#      attachment_properties: {
        # This hash is deep merged with the existing properties set using the
        # other properties above. This allows your own fields properties to be
        # appended to the existing fields that were created using the `payload`
        # property for instance.
#        thumb_url: "http://example.com/path/to/thumb.png",
#        fields: [{
#          title: "My Field",
#          value: "My Value",
#          short: true
#        }]
#      }
    )
  end

  desc "Synchronize certificates"
  lane :certificates do
    match(git_branch: "team_mandarin",
          app_identifier: ["no.mandarin.travistest"],
          readonly: true,
          clone_branch_directly: true)
  end

end
